In [23]:
from pathlib import Path
import pandas as pd
from hydra import compose, initialize
from ergochemics.draw import draw_reaction, draw_molecule
from ergochemics.standardize import hash_compound
from IPython.display import SVG
from rdkit import Chem
import yaml
from collections import defaultdict

with initialize(version_base=None, config_path="../configs/filepaths"):
    cfg = compose("filepaths")

In [24]:
mi_rxns = pd.read_parquet(Path(cfg.raw_data) / "mapped_known_reactions_x_mechinformed_rules.parquet")
rc0_rxns = pd.read_parquet(Path(cfg.raw_data) / "mapped_known_reactions_x_rc_plus_0_rules.parquet")
all_rxns = pd.Series(list(set(mi_rxns["smarts"]).union(set(rc0_rxns["smarts"]))))
rxn_counts = defaultdict(int)
for smarts in all_rxns:
    lhs, rhs = [side.split(".") for side in smarts.split(">>")]
    for elt in set(lhs).union(set(rhs)):
        rxn_counts[hash_compound(elt)] += 1

In [25]:
cpds = pd.read_parquet(Path(cfg.raw_data) / "known_compounds.parquet")
cpds.head()

,id,smiles,name,chebi_id,n_atoms
0,df58248c414f342c81e056b40bee12d17a08bf61,*,A,CHEBI:13193,1
1,bc2f74c22f98f7b6ffbc2f67453dbfa99bce9a32,**,RX,CHEBI:17792,2
2,e8ecd17bfc980925ff0b634bd13104c09dc4591f,*C,an alkane,CHEBI:18310,2
3,b219689f21c828e7f057ef453af1187baa98fbf3,*C#N,a nitrile,CHEBI:18379,3
4,94295b0379859ca57b86c85b0768526c711fe762,*C(*)(O)C(*)(*)O,an ethanediol,CHEBI:140594,8

In [26]:
cpds["rxn_count"] = cpds["id"].map(rxn_counts).fillna(0).astype(int)
cpds.sort_values(by="rxn_count", ascending=False, inplace=True)
cpds.head(20)

,id,smiles,name,chebi_id,n_atoms,rxn_count
8703,08a914cde05039694ef0194d9ee79ff9a79dde33,O,H2O,CHEBI:15377,1,9378
2007,795ce8b8f679817da1f0333c1a7ab70424422dd2,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,CoA,CHEBI:57287,48,3987
8679,07e48b419b37606b338ba3e838a8e5f56e1cef31,Nc1ncnc2c1ncn2C1OC(COP(=O)(O)OP(=O)(O)OP(=O)(O...,ATP,CHEBI:30616,31,2889
7961,da7b7aacec3c6f733a01920b971ac0deda5d3303,NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC...,NADP(+),CHEBI:58349,48,2604
7907,27e471428018c3779a1b13dec34fcbc3d80f6c28,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,NADPH,CHEBI:57783,48,2582
7959,599b0cd59ed43643b07bd6f1b3284abcbbb20811,NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC...,NAD(+),CHEBI:57540,44,2545
7904,7a1e0d8109d1cad180288524e8d50ef4aee3a40d,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,NADH,CHEBI:57945,44,2394
9743,cd67f644cdcbc3175749023bdcb6d22159a5a57c,O=P(O)(O)O,phosphate,CHEBI:43474,5,2038
8650,d149421ac53cc62325e84c1688210e5ba639cbaf,Nc1ncnc2c1ncn2C1OC(COP(=O)(O)OP(=O)(O)O)C(O)C1O,ADP,CHEBI:456216,27,2017
9806,15b21be91dee61fcae45fcceab54182d7f4ab244,O=P(O)(O)OP(=O)(O)O,diphosphate,CHEBI:33019,9,1902
9740,1aa818910461f5961959eb05dd06b8f7a4fbbb9f,O=O,O2,CHEBI:15379,2,1901
10021,032ad4a30e62a98cc92a81fc4e6d352006f30fdd,O=c1ccn(C2OC(COP(=O)(O)OP(=O)(O)O)C(O)C2O)c(=O...,UDP,CHEBI:58223,25,1875
7419,e6490b8cb18f68ed72b12d82460b1384c017d3c6,C[S+](CCC(N)C(=O)O)CC1OC(n2cnc3c(N)ncnc32)C(O)C1O,S-adenosyl-L-methionine,CHEBI:59789,27,1842
8691,eef113d8ad6695378d0caebf7bae3a67b60c6323,Nc1ncnc2c1ncn2C1OC(CSCCC(N)C(=O)O)C(O)C1O,S-adenosyl-L-homocysteine,CHEBI:57856,26,1802
9598,17d2ab53c78bed104290bde729ad657b5da216bb,O=C=O,CO2,CHEBI:16526,3,1374
10023,5bfb99425d410f7971f0aa0f48895479d9a43c0c,O=c1ccn(C2OC(COP(=O)(O)OP(=O)(O)OC3OC(CO)C(O)C...,UDP-alpha-D-glucose,CHEBI:58885,36,1097
8617,4ea34a41c2091b9cd312119934909d0fb3217dc8,Nc1ncnc2c1ncn2C1OC(COP(=O)(O)O)C(O)C1O,AMP,CHEBI:456215,23,1086
1930,b3d108052f15c3e212df2bd1df03c428da5b5957,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,acetyl-CoA,CHEBI:57288,51,949
7732,b51a60734da64be0e618bacbea2865a8a7dcd669,N,NH4(+),CHEBI:28938,1,855
10173,a96e088ce21c364e21e6ad6ef98ad04c78a93725,OO,H2O2,CHEBI:16240,2,590

In [27]:
default_sources = cpds.iloc[:20]["name"].values.tolist()

In [28]:
cpds["n_atoms"] = cpds["smiles"].apply(lambda x: Chem.MolFromSmiles(x).GetNumAtoms())
cpds.sort_values(by="n_atoms", ascending=True, inplace=True)
cpds.head(10)

[15:22:01] WARNING: not removing hydrogen atom with dummy atom neighbors
[15:22:01] WARNING: not removing hydrogen atom with dummy atom neighbors
[15:22:01] Unusual charge on atom 0 number of radical electrons set to zero
[15:22:01] WARNING: not removing hydrogen atom with dummy atom neighbors
[15:22:01] Unusual charge on atom 0 number of radical electrons set to zero

,id,smiles,name,chebi_id,n_atoms,rxn_count
8703,08a914cde05039694ef0194d9ee79ff9a79dde33,O,H2O,CHEBI:15377,1,9378
7732,b51a60734da64be0e618bacbea2865a8a7dcd669,N,NH4(+),CHEBI:28938,1,855
10536,9feed07c52dc52431b11eb941fe5ca9a2b4300fb,[Cu+],Cu(+),CHEBI:49552,1,0
10535,f5869f56736fc822ac2dbee43cff3ff7d8cfff45,[Cu+2],Cu(2+),CHEBI:29036,1,0
10537,e0bafc74c3421ac1da0481a7128fc09d5ab7cfc1,[F-],fluoride,CHEBI:17051,1,0
10531,825a95e02d44036cef84801c1561cf7712ee921f,[Cl-],chloride,CHEBI:17996,1,0
10555,3d56d75ba7d0475a3195b58edf46f5f9ee109fdf,[Ni+2],Ni(2+),CHEBI:49786,1,0
10534,9c54dc8891f6802eca1e53f74126e6b6487c86d0,[Cr+6],Cr(6+),CHEBI:33007,1,0
10529,786d4407ec3ae1b08b364a8871fa86c49a7a1d89,[Ca+2],Ca(2+),CHEBI:29108,1,0
10530,05c714ef71a4abd33cc057e44984c3404e492816,[Cd+2],Cd(2+),CHEBI:48775,1,0

In [29]:
default_sources.extend(["hydrogen sulfide", "methane"])

In [30]:
with open(Path(cfg.configs) / "sources" / "default.yaml", "w") as f:
    yaml.dump({"source_names": default_sources}, f)