In [21]:
from pathlib import Path
import pandas as pd
from hydra import compose, initialize
from ergochemics.draw import draw_reaction, draw_molecule
from IPython.display import SVG
from rdkit import Chem
import yaml

with initialize(version_base=None, config_path="../configs/filepaths"):
    cfg = compose("filepaths")

In [22]:
cpds = pd.read_csv(Path(cfg.interim_data) / "compounds.csv")
cpds.head()

,id,smiles,name,rxn_count,n_atoms
0,0,*C#N,a nitrile,4,3
1,1,*C(*)S,R'C(R)SH,2,4
2,2,*C(*)SSC(*)*,R'C(R)S-S(R)CR',2,8
3,3,*C(=Cc1c(*)c(*)c(*)c(*)c1*)C(=O)c1c(*)c(*)c(*)...,a (E)-2'-hydroxy-chalcone,2,27
4,4,*C(=N)C(=O)O,a 2-iminocarboxylate,2,6

In [23]:
cpds.sort_values(by="rxn_count", ascending=False, inplace=True)
cpds.head(20)

,id,smiles,name,rxn_count,n_atoms
7811,7811,O,H2O,6514,1
2308,2308,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,CoA,2327,48
7148,7148,NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC...,NADP(+),1862,48
7095,7095,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,NADPH,1850,48
8678,8678,O=O,O2,1839,2
7793,7793,Nc1ncnc2c1ncn2C1OC(COP(=O)(O)OP(=O)(O)OP(=O)(O...,ATP,1822,31
7146,7146,NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC...,NAD(+),1672,44
7092,7092,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,NADH,1578,44
8741,8741,O=P(O)(O)OP(=O)(O)O,diphosphate,1389,9
8681,8681,O=P(O)(O)O,phosphate,1324,5
7766,7766,Nc1ncnc2c1ncn2C1OC(COP(=O)(O)OP(=O)(O)O)C(O)C1O,ADP,1192,27
8553,8553,O=C=O,CO2,1180,3
6707,6707,C[S+](CCC(N)C(=O)O)CC1OC(n2cnc3c(N)ncnc32)C(O)C1O,S-adenosyl-L-methionine,1144,27
7804,7804,Nc1ncnc2c1ncn2C1OC(CSCCC(N)C(=O)O)C(O)C1O,S-adenosyl-L-homocysteine,1107,26
8906,8906,O=c1ccn(C2OC(COP(=O)(O)OP(=O)(O)O)C(O)C2O)c(=O...,UDP,964,25
7734,7734,Nc1ncnc2c1ncn2C1OC(COP(=O)(O)O)C(O)C1O,AMP,758,23
6946,6946,N,NH4(+),687,1
9044,9044,OO,H2O2,588,2
8908,8908,O=c1ccn(C2OC(COP(=O)(O)OP(=O)(O)OC3OC(CO)C(O)C...,UDP-alpha-D-glucose,570,36
8191,8191,O=C(O)CCC(=O)C(=O)O,2-oxoglutarate,558,10

In [24]:
default_sources = cpds.iloc[:20]["name"].values.tolist()
default_sources.remove("2-oxoglutarate")

In [25]:
cpds["n_atoms"] = cpds["smiles"].apply(lambda x: Chem.MolFromSmiles(x).GetNumAtoms())
cpds.sort_values(by="n_atoms", ascending=True, inplace=True)
cpds.head(10)

        id smiles                  name  rxn_count  n_atoms
7811  7811      O                   H2O       6514        1
1416  1416      C               methane          6        1
9106  9106      S      hydrogen sulfide         40        1
6946  6946      N                NH4(+)        687        1
6032  6032     CO              methanol         62        2
1362  1362     *S               a thiol          4        2
6590  6590     CS          methanethiol         16        2
1070  1070     *O  an aliphatic alcohol         64        2
1417  1417    C#C             acetylene          2        2
5884  5884     CN           methylamine         38        2

In [26]:
default_sources.extend(["hydrogen sulfide", "methane"])

In [27]:
with open(Path(cfg.configs) / "sources" / "default.yaml", "w") as f:
    yaml.dump({"source_names": default_sources}, f)