In [1]:
import networkx as nx
from pprint import pprint
import json
import pandas as pd
from krxns.network import ReactionNetwork

In [2]:
G_str = nx.MultiDiGraph()
G_str.add_node("A", **{'foo': 'bar'})
G_str.add_node("B")
print(G_str.add_edge("A", "B", key='r1', data={"rate": 0.8, "type": "forward"}))
print(G_str.add_edge("A", "B", key='r2', data={"rate": 0.3, "type": "forward"}))
print(G_str.add_edge("A", "B", key='r3', data={"rate": 1.0, "type": "forward"}))

r1
r2
r3

In [3]:
edges_between_A_B = G_str.get_edge_data("A", "B")
pprint(edges_between_A_B)

{'r1': {'data': {'rate': 0.8, 'type': 'forward'}},
 'r2': {'data': {'rate': 0.3, 'type': 'forward'}},
 'r3': {'data': {'rate': 1.0, 'type': 'forward'}}}

In [4]:
G_str.edges['A', 'B', 'r2']

{'data': {'rate': 0.3, 'type': 'forward'}}

In [5]:
[(idx, data) for idx, data in G_str.nodes(data=True)]

[('A', {'foo': 'bar'}), ('B', {})]

In [6]:
G_str.nodes['A']

{'foo': 'bar'}

In [7]:
'B' in G_str.nodes

True

In [8]:
max(G_str.nodes)

'B'

In [9]:
df = pd.read_parquet("../data/raw/mapped_known_reactions_x_rc_plus_0_rules.parquet")
df.head()

,rxn_id,smarts,am_smarts,rule,template_aidxs,rule_id
0,410,*C#N.O>>*C(N)=O,[*:4][C:2]#[N:1].[OH2:3]>>[*:4][C:2]([NH2:1])=...,[#6:1]#[#7:2].[#8:3]>>[#7:2]-[#6:1]=[#8:3],"1,2;0>>1,2,3",549
1,411,*C#N.O>>*C=NO,[*:4][C:1]#[N:2].[OH2:3]>>[*:4][CH:1]=[N:2][OH:3],[#6:1]#[#7:2].[#8:3]>>[#6:1]=[#7:2]-[#8:3],"1,2;0>>1,2,3",785
2,421,*C(*)S.*C(*)S.O=O>>*C(*)SSC(*)*.OO,[*:4][CH:3]([*:5])[SH:1].[*:7][CH:6]([*:8])[SH...,[#16:1].[#16:2].[#8:3]=[#8:4]>>[#16:1]-[#16:2]...,"3;3;0,1>>3,4;0,1",747
3,422,*C(*)SSC(*)*.OO>>*C(*)S.*C(*)S.O=O,[*:3][CH:2]([*:4])[S:1][S:5][CH:6]([*:7])[*:8]...,[#16:1]-[#16:2].[#8:3]-[#8:4]>>[#16:1].[#16:2]...,"3,4;0,1>>3;3;0,1",225
4,424,*C(=Cc1c(*)c(*)c(*)c(*)c1*)C(=O)c1c(*)c(*)c(*)...,[*:16][C:1](=[CH:2][c:17]1[c:18]([*:20])[c:21]...,([#8:1].[#6:2]=[#6:3])>>[#6:2]-[#6:3]-[#8:1],"26,1,2>>7,8,21",412

In [10]:
kcs = pd.read_parquet("../data/raw/known_compounds.parquet")
kcs.head()

   id            smiles           name      chebi_id  n_atoms
0   0                 *              A   CHEBI:13193        1
1   1                **             RX   CHEBI:17792        2
2   2                *C      an alkane   CHEBI:18310        2
3   3              *C#N      a nitrile   CHEBI:18379        3
4   4  *C(*)(O)C(*)(*)O  an ethanediol  CHEBI:140594        8

In [11]:
nodes = [
    (0, {'grouped_predecessors': {'R1': [1,], 'R2': [2,], 'R3': [3, 4]}, 'tot_rnmc': {'R1': 1.0, 'R2': 1.0, 'R3': 1.0}}),
    (1, {'grouped_predecessors': {'R4': [5,], 'R5': [6, 7]}, 'tot_rnmc': {'R4': 1.0, 'R5': 1.0}}),
    (2, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (3, {'grouped_predecessors': {'R6': [8, 9]}, 'tot_rnmc': {'R6': 0.8}}),
    (4, {'grouped_predecessors': {'R7': [10,]}, 'tot_rnmc': {'R7': 1.0}}),
    (5, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (6, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (7, {'grouped_predecessors': {'R8': [11,]}, 'tot_rnmc': {'R8': 0.9}}),
    (8, {'grouped_predecessors': {'R9': [12,]}, 'tot_rnmc': {'R9': 1.0}}),
    (9, {'grouped_predecessors': {'R10': [13,]}, 'tot_rnmc': {'R10': 0.95}}),
    (10, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (11, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (12, {'grouped_predecessors': {'R11': [14,]}, 'tot_rnmc': {'R11': 0.85}}),
    (13, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (14, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
]

edges = [
    (1, 0, {'rid': 'R1'}),
    (2, 0, {'rid': 'R2'}),
    (3, 0, {'rid': 'R3'}),
    (4, 0, {'rid': 'R3'}),
    (5, 1, {'rid': 'R4'}),
    (6, 1, {'rid': 'R5'}),
    (7, 1, {'rid': 'R5'}),
    (8, 3, {'rid': 'R6'}),
    (9, 3, {'rid': 'R6'}),
    (10, 4, {'rid': 'R7'}),
    (11, 7, {'rid': 'R8'}),
    (12, 8, {'rid': 'R9'}),
    (13, 9, {'rid': 'R10'}),
    (14, 12, {'rid': 'R11'}),

]

target = 0
sources = {6, 10, 11, 13, 14}
max_leaves = 5
max_depth = 5

G = nx.MultiDiGraph()
G.add_nodes_from(nodes)
G.add_edges_from(edges)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [12]:
G = ReactionNetwork.from_json('../data/processed/known_reaction_network.json')

In [16]:
G.nodes[1]

{'smiles': '*C#N',
 'name': 'a nitrile',
 'source': False,
 'grouped_predecessors': {'1770': [0], '2247': [6649]},
 'tot_rnmc': {'1770': 0.75, '2247': 0.75}}

In [15]:
G.get_edge_data(0, 1)

{1770: {'reaction_id': 1770,
  'pnmc': 1.0,
  'rnmc': 0.75,
  'am_smarts': '[*:3][C:1]([NH2:2])=[O:4]>>[*:3][C:1]#[N:2].[OH2:4]'}}

In [18]:
G.edges[0, 1, 1770]

{'reaction_id': 1770,
 'pnmc': 1.0,
 'rnmc': 0.75,
 'am_smarts': '[*:3][C:1]([NH2:2])=[O:4]>>[*:3][C:1]#[N:2].[OH2:4]'}

In [ ]:
df.loc[df['rxn_id'] == 410, 'smarts']

0    *C#N.O>>*C(N)=O
Name: smarts, dtype: object

In [ ]:
'''
- Iterate over nodes
    - Iterate over reactions in node attr
        - Iterate over compounds in grouped_predecessors
            - Collect pnmc for each predecessor & sources (cache)
            - Mark edges (i, j) for deletion if fail rnmc and pnmc criteria
        - Iterate over grouped_predecessors
            - Mark edges (i, j) for deletion if fail pnmc + source_mass < augmented mass criteria
- Remove marked edges
'''