In [9]:
import networkx as nx
from pprint import pprint
import json
import pandas as pd
from krxns.network import ReactionNetwork

In [42]:
G_str = nx.MultiDiGraph()
G_str.add_node("A", **{'foo': 'bar'})
G_str.add_node("B")
print(G_str.add_edge("A", "B", data={"rate": 1.0, "type": "forward"}))
print(G_str.add_edge("A", "B", data={"rate": 1.0, "type": "forward"}))
print(G_str.add_edge("A", "B", data={"rate": 1.0, "type": "forward"}))

0
1
2

In [43]:
[(idx, data) for idx, data in G_str.nodes(data=True)]

[('A', {'foo': 'bar'}), ('B', {})]

In [44]:
G_str.nodes['A']

{'foo': 'bar'}

In [26]:
'B' in G_str.nodes

True

In [20]:
max(G_str.nodes)

ValueError: max() iterable argument is empty

In [45]:
df = pd.read_parquet("../data/raw/mapped_known_reactions_x_rc_plus_0_rules.parquet")
df.head()

,rxn_id,smarts,am_smarts,rule,template_aidxs,rule_id
0,410,*C#N.O>>*C(N)=O,[*:4][C:2]#[N:1].[OH2:3]>>[*:4][C:2]([NH2:1])=...,[#6:1]#[#7:2].[#8:3]>>[#7:2]-[#6:1]=[#8:3],"1,2;0>>1,2,3",549
1,411,*C#N.O>>*C=NO,[*:4][C:1]#[N:2].[OH2:3]>>[*:4][CH:1]=[N:2][OH:3],[#6:1]#[#7:2].[#8:3]>>[#6:1]=[#7:2]-[#8:3],"1,2;0>>1,2,3",785
2,421,*C(*)S.*C(*)S.O=O>>*C(*)SSC(*)*.OO,[*:4][CH:3]([*:5])[SH:1].[*:7][CH:6]([*:8])[SH...,[#16:1].[#16:2].[#8:3]=[#8:4]>>[#16:1]-[#16:2]...,"3;3;0,1>>3,4;0,1",747
3,422,*C(*)SSC(*)*.OO>>*C(*)S.*C(*)S.O=O,[*:3][CH:2]([*:4])[S:1][S:5][CH:6]([*:7])[*:8]...,[#16:1]-[#16:2].[#8:3]-[#8:4]>>[#16:1].[#16:2]...,"3,4;0,1>>3;3;0,1",225
4,424,*C(=Cc1c(*)c(*)c(*)c(*)c1*)C(=O)c1c(*)c(*)c(*)...,[*:16][C:1](=[CH:2][c:17]1[c:18]([*:20])[c:21]...,([#8:1].[#6:2]=[#6:3])>>[#6:2]-[#6:3]-[#8:1],"26,1,2>>7,8,21",412

In [7]:
kcs = pd.read_parquet("../data/raw/known_compounds.parquet")
kcs.head()

   id            smiles           name      chebi_id  n_atoms
0   0                 *              A   CHEBI:13193        1
1   1                **             RX   CHEBI:17792        2
2   2                *C      an alkane   CHEBI:18310        2
3   3              *C#N      a nitrile   CHEBI:18379        3
4   4  *C(*)(O)C(*)(*)O  an ethanediol  CHEBI:140594        8

In [12]:
nodes = [
    (0, {'grouped_predecessors': {'R1': [1,], 'R2': [2,], 'R3': [3, 4]}, 'tot_rnmc': {'R1': 1.0, 'R2': 1.0, 'R3': 1.0}}),
    (1, {'grouped_predecessors': {'R4': [5,], 'R5': [6, 7]}, 'tot_rnmc': {'R4': 1.0, 'R5': 1.0}}),
    (2, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (3, {'grouped_predecessors': {'R6': [8, 9]}, 'tot_rnmc': {'R6': 0.8}}),
    (4, {'grouped_predecessors': {'R7': [10,]}, 'tot_rnmc': {'R7': 1.0}}),
    (5, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (6, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (7, {'grouped_predecessors': {'R8': [11,]}, 'tot_rnmc': {'R8': 0.9}}),
    (8, {'grouped_predecessors': {'R9': [12,]}, 'tot_rnmc': {'R9': 1.0}}),
    (9, {'grouped_predecessors': {'R10': [13,]}, 'tot_rnmc': {'R10': 0.95}}),
    (10, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (11, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (12, {'grouped_predecessors': {'R11': [14,]}, 'tot_rnmc': {'R11': 0.85}}),
    (13, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
    (14, {'grouped_predecessors': {}, 'tot_rnmc': {}}),
]

edges = [
    (1, 0, {'rid': 'R1'}),
    (2, 0, {'rid': 'R2'}),
    (3, 0, {'rid': 'R3'}),
    (4, 0, {'rid': 'R3'}),
    (5, 1, {'rid': 'R4'}),
    (6, 1, {'rid': 'R5'}),
    (7, 1, {'rid': 'R5'}),
    (8, 3, {'rid': 'R6'}),
    (9, 3, {'rid': 'R6'}),
    (10, 4, {'rid': 'R7'}),
    (11, 7, {'rid': 'R8'}),
    (12, 8, {'rid': 'R9'}),
    (13, 9, {'rid': 'R10'}),
    (14, 12, {'rid': 'R11'}),

]

target = 0
sources = {6, 10, 11, 13, 14}
max_leaves = 5
max_depth = 5

G = nx.MultiDiGraph()
G.add_nodes_from(nodes)
G.add_edges_from(edges)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
with open("toy_graph.json", "r") as f:
    data = json.load(f)

G = nx.node_link_graph(data, edges="edges")

/home/stef/krxns/.venv/lib/python3.13/site-packages/networkx/readwrite/json_graph/node_link.py:290: FutureWarning:
The default value will be changed to `edges="edges" in NetworkX 3.6.

To make this warning go away, explicitly set the edges kwarg, e.g.:

  nx.node_link_graph(data, edges="links") to preserve current behavior, or
  nx.node_link_graph(data, edges="edges") for forward compatibility.
  warnings.warn(

In [72]:
with open('../data/processed/known_reaction_network.json', 'r') as f:
    data = json.load(f)

G = nx.node_link_graph(data, edges='edges')

In [76]:
G.nodes(data=True)[0]

{'smiles': '*C(N)=O',
 'name': 'an aliphatic primary amide',
 'source': False,
 'grouped_predecessors': {'410': [1, 2], '1241': [129, 94]},
 'tot_rnmc': {'410': 1.0, '1241': 0.8}}

In [77]:
G.nodes(data=True)[1]

{'smiles': '*C#N',
 'name': 'a nitrile',
 'source': False,
 'grouped_predecessors': {'1770': [0], '2247': [6649]},
 'tot_rnmc': {'1770': 0.75, '2247': 0.75}}

In [78]:
G.nodes[2]

{'smiles': 'O',
 'name': 'H2O',
 'source': False,
 'grouped_predecessors': {'435': [19, 9],
  '436': [21, 9],
  '529': [34, 33],
  '530': [32, 33],
  '531': [33, 94],
  '535': [34, 51],
  '536': [32, 51],
  '537': [51, 94],
  '543': [72, 74],
  '633': [124, 125],
  '671': [157, 159],
  '672': [157, 161],
  '686': [167, 168],
  '689': [167, 138],
  '692': [174, 167],
  '713': [174, 177],
  '723': [186, 176],
  '730': [174, 176],
  '742': [191, 178],
  '744': [193, 178],
  '752': [174, 178],
  '753': [191, 187],
  '756': [193, 187],
  '764': [174, 187],
  '797': [191, 190],
  '799': [193, 190],
  '804': [191, 195],
  '806': [193, 195],
  '838': [193, 232],
  '841': [193, 234],
  '883': [193, 260],
  '884': [191, 192],
  '888': [191, 197],
  '912': [174, 214],
  '914': [193, 194],
  '920': [193, 200],
  '926': [193, 268],
  '936': [191, 261],
  '945': [191, 262],
  '946': [191, 262],
  '952': [191, 263],
  '955': [191, 264],
  '963': [191, 265],
  '970': [191, 266],
  '971': [191, 266],
  '977': [191, 267],
  '978': [191, 267],
  '1014': [191, 294],
  '1017': [191, 281],
  '1025': [191, 284],
  '1030': [191, 288],
  '1036': [191, 290],
  '1083': [312, 313],
  '1092': [174, 318],
  '1135': [327, 180],
  '1137': [327, 138],
  '1138': [136, 138],
  '1143': [331, 332],
  '1153': [138, 335],
  '1154': [335, 337],
  '1156': [335, 340],
  '1175': [345, 129],
  '1177': [347, 129],
  '1178': [349, 129],
  '1179': [351, 129],
  '1186': [352, 129],
  '1187': [353, 129],
  '1188': [354, 129],
  '1192': [129, 179],
  '1193': [129, 269],
  '1194': [129, 355],
  '1195': [358, 129],
  '1199': [129, 363],
  '1212': [129, 140],
  '1213': [129, 99],
  '1214': [129, 173],
  '1215': [129, 366],
  '1216': [129, 131],
  '1217': [369, 129],
  '1218': [371, 129],
  '1219': [373, 129],
  '1220': [375, 129],
  '1221': [377, 129],
  '1222': [379, 129],
  '1223': [381, 129],
  '1224': [383, 129],
  '1225': [385, 129],
  '1227': [129, 188],
  '1228': [129, 272],
  '1229': [129, 163],
  '1233': [129, 386],
  '1235': [129, 150],
  '1236': [129, 388],
  '1241': [129, 94],
  '1243': [129, 121],
  '1245': [129, 5],
  '1246': [129, 142],
  '1247': [129, 146],
  '1248': [129, 144],
  '1249': [129, 152],
  '1250': [129, 392],
  '1251': [129, 21],
  '1252': [129, 323],
  '1253': [129, 325],
  '1254': [129, 334],
  '1255': [129, 148],
  '1256': [129, 339],
  '1258': [129, 343],
  '1264': [129, 395],
  '1265': [129, 396],
  '1268': [129, 398],
  '1327': [152, 345],
  '1336': [413, 351],
  '1341': [415, 416],
  '1447': [346, 138],
  '1448': [346, 138],
  '1466': [446, 138],
  '1481': [442, 138],
  '1482': [442, 138],
  '1489': [443, 138],
  '1494': [451, 138],
  '1540': [350, 138],
  '1606': [397, 138],
  '1631': [152, 427],
  '1746': [477, 121],
  '1753': [174, 479],
  '1770': [0],
  '1780': [485],
  '1782': [485, 363],
  '1783': [7, 485],
  '1791': [491, 485],
  '1794': [94, 485, 118],
  '1809': [485, 487],
  '1867': [501, 168],
  '1869': [501, 138],
  '1878': [510, 332],
  '1899': [519, 517],
  '1905': [120],
  '1931': [528, 529],
  '1932': [531, 529],
  '1952': [539, 138],
  '1953': [539, 138],
  '1954': [542, 539],
  '1956': [540, 544],
  '1957': [546, 544],
  '1958': [548, 544],
  '1959': [544, 550],
  '1960': [138, 544],
  '1967': [540, 138],
  '1968': [138, 540],
  '1969': [328, 540],
  '1980': [555, 138],
  '1991': [560, 541],
  '1993': [552, 323],
  '1994': [552, 564],
  '1995': [566, 552],
  '2044': [574],
  '2077': [584],
  '2078': [586],
  '2082': [588, 589],
  '2088': [591],
  '2091': [593, 594],
  '2092': [595, 594],
  '2095': [594],
  '2125': [602, 138],
  '2147': [618, 589],
  '2183': [624, 625],
  '2185': [138, 624],
  '2187': [339, 628],
  '2217': [639, 625],
  '2218': [639, 138],
  '2219': [312, 640],
  '2220': [339, 640],
  '2319': [642],
  '2373': [519, 656],
  '2407': [663, 658],
  '2467': [665, 323],
  '2468': [665, 325],
  '2470': [667, 144],
  '2481': [669, 164],
  '2482': [668, 144],
  '2485': [668, 671],
  '2514': [193, 675],
  '2515': [677, 675],
  '2522': [675, 360],
  '2525': [675, 138],
  '2617': [193, 727],
  '2620': [729, 730],
  '2628': [174, 733],
  '2652': [174, 747],
  '2653': [174, 747],
  '2658': [174, 748],
  '2659': [174, 752],
  '2662': [174, 749],
  '2664': [174, 754],
  '2666': [174, 751],
  '2670': [174, 753],
  '2672': [174, 755],
  '2673': [757, 755],
  '2678': [174, 756],
  '2682': [174, 758],
  '2684': [174, 759],
  '2702': [768, 94],
  '2704': [770, 768],
  '2711': [771, 772],
  '2750': [776, 772],
  '2752': [776, 94],
  '2755': [776, 144],
  '2757': [770, 776],
  '2759': [778, 94],
  '2762': [778, 787],
  '2763': [778, 148],
  '2770': [174, 801],
  '2822': [519, 804],
  '2823': [822, 804, 684],
  '2829': [831, 804],
  '2830': [832, 804, 684],
  '2835': [835, 804],
  '2837': [836, 804, 684],
  '2840': [840, 804],
  '2841': [841, 804, 684],
  '2846': [848, 804, 684],
  '2847': [849, 804, 684],
  '2848': [851, 804, 684],
  '2849': [853, 804, 684],
  '2850': [854, 804, 684],
  '2852': [855, 804, 684],
  '2857': [860, 804, 684],
  '2858': [861, 804, 684],
  '2859': [862, 804, 684],
  '2860': [864, 804, 684],
  '2861': [866, 804, 684],
  '2876': [875, 804],
  '3000': [887, 138],
  '3005': [890, 138],
  '3009': [886, 138],
  '3080': [899, 94],
  '3090': [193, 473],
  '3091': [677, 473],
  '3096': [473, 904],
  '3104': [915, 473],
  '3111': [473, 168],
  '3117': [770, 473],
  '3120': [473, 138],
  '3206': [963, 138],
  '3241': [972, 114],
  '3245': [975, 114],
  '3269': [981, 114],
  '3270': [983, 114],
  '3271': [985, 114],
  '3286': [1007, 114],
  '3291': [413, 114],
  '3293': [1011, 114],
  '3296': [1014, 114],
  '3302': [1021, 114],
  '3307': [415, 114],
  '3314': [1032, 114],
  '3494': [504],
  '3567': [972],
  '3572': [1085],
  '3581': [1086],
  '3588': [1088],
  '3590': [1090],
  '3593': [1092],
  '3596': [1094],
  '3599': [1096],
  '3601': [1099],
  '3605': [1017],
  '3608': [1024],
  '3610': [1103],
  '3629': [1130, 772],
  '3749': [519, 906],
  '3831': [415, 362],
  '3895': [1163, 772],
  '3961': [1165, 772],
  '3993': [138, 1170],
  '3994': [138, 1172],
  '4011': [360, 1177],
  '4013': [770, 1177],
  '4018': [138, 1177],
  '4019': [332, 1177],
  '4094': [1199, 1154],
  '4103': [124, 1197],
  '4108': [415, 1203],
  '4115': [1208, 363],
  '4116': [519, 363],
  '4119': [1211, 363],
  '4120': [1213, 363],
  '4121': [1215, 363],
  '4122': [1217, 363],
  '4123': [1007, 363],
  '4124': [1011, 363],
  '4125': [1014, 363],
  '4126': [1021, 363],
  '4127': [415, 363],
  '4128': [1032, 363],
  '4138': [1227, 363],
  '4141': [138, 363],
  '4142': [363, 337],
  '4145': [1230, 363],
  '4146': [1232, 363],
  '4170': [1237, 519],
  '4174': [138, 593],
  '4258': [94, 1249],
  '4361': [1286, 589],
  '4362': [1287, 589],
  '4365': [1290, 589],
  '4366': [1293, 589],
  '4367': [1295, 589],
  '4368': [681, 589],
  '4369': [122, 589],
  '4373': [328, 589],
  '4375': [1287, 1299],
  '4376': [1290, 1299],
  '4377': [1287, 1302],
  '4378': [1290, 1302],
  '4392': [328, 1306],
  '4394': [328, 1307],
  '4395': [1309, 904],
  '4396': [1309, 1310],
  '4397': [1309, 1311],
  '4418': [814, 1315],
  '4419': [814, 1316],
  '4421': [814, 138],
  '4423': [817, 138],
  '4425': [819, 138],
  '4469': [138, 560],
  '4470': [1324, 323],
  '4471': [1324, 564],
  '4472': [1324, 360],
  '4475': [1324, 528],
  '4477': [1330, 360],
  '4489': [1331, 1332],
  '4493': [770, 1334],
  '4525': [94, 1333],
  '4583': [1352, 929],
  '4586': [193, 1360],
  '4588': [1361, 1360],
  '4593': [519, 1362],
  '4660': [138, 1395],
  '4663': [1397, 168],
  '4710': [186, 1401],
  '4718': [1402, 138],
  '4755': [1399, 519],
  '4756': [1399, 168],
  '4768': [519, 1404],
  '4799': [1407],
  '4818': [7, 1420],
  '4823': [7, 1153],
  '4825': [7, 1423],
  '4830': [7, 150],
  '4836': [7, 1434],
  '4838': [7, 1437],
  '4840': [7, 152],
  '4843': [7, 1154],
  '4847': [7, 21],
  '4850': [7, 323],
  '4852': [7, 325],
  '4854': [7, 334],
  '4969': [144, 1472],
  '4973': [1473, 334],
  '4981': [1474, 334],
  '5035': [519, 1490],
  '5107': [1514, 121],
  '5114': [1518, 121],
  '5181': [1590],
  '5191': [1592],
  '5193': [1594],
  '5196': [1597, 5],
  '5219': [328, 1599],
  '5223': [1601, 121],
  '5224': [1601, 5],
  '5256': [1607],
  '5319': [138, 1618],
  '5350': [519, 1624],
  '5373': [1627, 94],
  '5828': [328, 1708],
  '5898': [1714, 94],
  '5899': [1714, 121],
  '5970': [328, 1723],
  '5972': [328, 1721],
  '5973': [328, 1726],
  '5974': [328, 1709],
  '5975': [328, 1728],
  '5978': [328, 1729],
  '5984': [328, 1730],
  '5986': [328, 1731],
  '5989': [121, 1719],
  '5990': [1719, 121],
  '6028': [1735, 5],
  '6065': [1227, 1737],
  '6066': [1227, 1737],
  '6072': [1227, 1742],
  '6079': [1227, 1740],
  '6097': [1743, 772],
  '6186': [1747, 174],
  '6188': [1749, 174],
  '6189': [1751, 174],
  '6190': [1753, 174],
  '6204': [1755, 1051],
  '6268': [1772, 772],
  '6434': [1783, 772],
  '6512': [1805, 1806],
  '6522': [328, 1810],
  '6525': [328, 1812],
  '6589': [94, 1825, 118],
  '6590': [1826, 1825],
  '6618': [559, 519],
  '6636': [559, 835],
  '6669': [559, 121, 94],
  '6676': [559, 94, 1848],
  '6692': [559, 121],
  '6748': [559, 1853],
  '6805': [1881, 5, 94],
  '6807': [1841, 121, 94],
  '6808': [1841, 5, 94],
  '6827': [1890, 121, 94],
  '6922': [1916, 5, 94],
  '6966': [1922, 15],
  '6976': [1922, 1853],
  '7001': [1928, 121, 94],
  '7002': [1928, 5, 94],
  '7008': [1932, 121, 94],
  '7020': [1938, 121, 94],
  '7021': [1940, 121, 94],
  '7022': [1942, 121, 94],
  '7028': [1919, 121, 94],
  '7048': [1957, 180],
  '7091': [1968, 144],
  '7138': [1996, 1998],
  '7185': [2022, 216],
  '7186': [2022, 106],
  '7197': [1434, 2034],
  '7204': [191, 519],
  '7205': [519, 191],
  '7209': [191, 2041],
  '7210': [191, 2043],
  '7211': [191, 2045],
  '7212': [191, 2046],
  '7213': [191, 2044],
  '7216': [191, 138],
  '7217': [191, 2049],
  '7227': [1647, 138],
  '7272': [193],
  '7273': [193, 2077],
  '7274': [2079, 193],
  '7279': [1361, 193],
  '7297': [2085, 1153],
  '7300': [2085, 138],
  '7301': [186, 2088],
  '7309': [677, 2049],
  '7315': [519, 2081],
  '7341': [835, 2082],
  '7342': [2082, 1361],
  '7356': [2108, 2109],
  '7367': [519, 2096],
  '7368': [519, 2105],
  '7371': [2112, 1153],
  '7398': [2133, 2134],
  '7399': [2133, 2136],
  '7404': [2140, 138],
  '7416': [2080, 332],
  '7426': [121, 2010],
  '7473': [107],
  '7554': [2195, 121],
  '7623': [519, 2245],
  '7628': [519, 15],
  '7637': [519, 2198],
  '7639': [519, 1421],
  '7640': [519, 140],
  '7641': [519, 2247],
  '7642': [519, 1966],
  '7652': [519, 131],
  '7656': [519, 2250],
  '7657': [519, 2252],
  '7659': [519, 1019],
  '7660': [519, 2255],
  '7661': [519, 2256],
  '7662': [519, 2258],
  '7663': [519, 2260],
  '7664': [2263, 519],
  '7665': [519, 2264],
  '7666': [519, 2266],
  '7667': [519, 2268],
  '7668': [519, 2270],
  '7669': [519, 2272],
  '7670': [519, 2274],
  '7671': [519, 386],
  '7672': [519, 772],
  '7675': [519, 2278],
  '7678': [519, 2280],
  '7681': [519, 150],
  '7682': [519, 312],
  '7683': [519, 2284],
  '7687': [519, 94],
  '7688': [519, 121],
  '7689': [519, 5],
  '7690': [519, 146],
  '7691': [519, 1987],
  '7693': [519, 1434],
  '7694': [519, 1976],
  '7695': [519, 2287],
  '7696': [519, 1978],
  '7700': [519, 1154],
  '7705': [519, 325],
  '7709': [519, 1361],
  '7710': [519, 2106],
  '7711': [519, 2111],
  '7712': [519, 2142],
  '7713': [519, 2130],
  '7714': [519, 2118],
  '7715': [519, 2192],
  '7716': [519, 1989],
  '7717': [519, 2196],
  '7718': [519, 787],
  '7719': [519, 2202],
  '7720': [519, 148],
  '7721': [519, 2205],
  '7722': [519, 2207],
  '7723': [519, 868],
  '7724': [519, 868],
  '7725': [519, 2213],
  '7726': [519, 343],
  '7727': [519, 793],
  '7728': [519, 1051],
  '7729': [519, 2228],
  '7730': [519, 2230],
  '7731': [519, 2238],
  '7732': [519, 607],
  '7733': [519, 2244],
  '7734': [770, 519],
  '7735': [770, 519],
  '7736': [770, 519],
  '7740': [519, 2292],
  '7742': [519, 825],
  '7743': [519, 2293],
  '7744': [519, 2295],
  '7747': [519, 1573],
  '7752': [519, 174],
  '7753': [519, 2299],
  '7754': [519, 2301],
  '7755': [519, 2303],
  '7772': [413, 2306],
  '7849': [2352, 2353],
  '7905': [1134, 185],
  '8017': [14, 2278],
  '8123': [14, 2425],
  '8125': [14, 1573],
  '8161': [1529, 121, 94],
  '8183': [2443, 15],
  '8184': [2443, 121],
  '8232': [2435],
  '8238': [138, 2448],
  '8240': [138, 2451],
  '8242': [2456, 121],
  '8247': [2458, 2459],
  '8263': [2466, 138],
  '8266': [2465, 138],
  '8270': [2469, 138],
  '8271': [2468, 2370],
  '8275': [2468, 138],
  '8285': [2462, 2192],
  '8291': [904, 185],
  '8296': [2474, 185],
  '8297': [2475, 185],
  '8299': [2477, 185],
  '8414': [2480, 15],
  '8416': [2372, 15],
  '8421': [2483, 15],
  '8424': [2486, 15],
  '8425': [2488, 15],
  '8427': [2491, 15],
  '8431': [2494, 15],
  '8433': [2496, 15],
  '8453': [2516, 15],
  '8455': [2517, 15],
  '8456': [2519, 15],
  '8460': [2521, 15],
  '8468': [2527, 15],
  '8470': [1782, 15],
  '8471': [2528, 15],
  '8472': [1794, 15],
  '8475': [1923, 15],
  '8500': [1211, 15],
  '8506': [2544, 15],
  '8511': [2377, 15],
  '8512': [2547, 15],
  '8523': [2552, 15],
  '8537': [2560, 15],
  '8569': [1213, 15],
  '8582': [1215, 15],
  '8586': [2590, 15],
  '8592': [1217, 15],
  '8597': [2598, 15],
  '8610': [2601, 15],
  '8654': [2647, 15],
  '8686': [2681, 15],
  '8691': [915, 15],
  '8705': [2699, 15],
  '8712': [1007, 15],
  '8719': [2711, 15],
  '8730': [413, 15],
  '8833': [2834, 15],
  '8837': [1011, 15],
  '8840': [2838, 15],
  '8841': [2840, 15],
  '8855': [1014, 15],
  '8860': [2853, 15],
  '8870': [1021, 15],
  '8903': [415, 15],
  '8945': [2918, 15],
  '8958': [1032, 15],
  '8984': [2947, 15],
  '8996': [2958, 15],
  '9005': [2965, 15],
  '9014': [2975, 15],
  '9069': [1820, 15],
  '9078': [2279, 15],
  '9109': [2413, 15],
  '9110': [2415, 15],
  '9111': [3046, 15],
  '9149': [3063, 15],
  '9220': [3090, 15],
  '9225': [3095, 15],
  '9236': [1955, 15],
  '9237': [2418, 15],
  '9238': [2419, 15],
  '9239': [1849, 15],
  '9240': [1849, 15],
  '9244': [1855, 15],
  '9245': [2421, 15],
  '9247': [2352, 15],
  '9248': [2422, 15],
  '9249': [3117, 15],
  '9250': [2423, 15],
  '9251': [3119, 15],
  '9252': [3121, 15],
  '9253': [3123, 15],
  '9254': [3124, 15],
  '9255': [3126, 15],
  '9258': [3130, 15],
  '9259': [3132, 15],
  '9260': [3134, 15],
  '9261': [3136, 15],
  '9262': [3137, 15],
  '9263': [3139, 15],
  '9264': [3141, 15],
  '9265': [3143, 15],
  '9269': [1930, 15],
  '9464': [3184, 5],
  '9614': [3165],
  '9616': [3167],
  '9621': [3169],
  '9623': [3171],
  '9625': [3173],
  '9627': [3175],
  '9629': [3177],
  '9634': [3179],
  '9637': [3181],
  '9639': [3182],
  '9644': [3195, 5],
  '9682': [3196],
  '9833': [831, 121],
  '9847': [3201],
  '9848': [3203, 138],
  '9868': [3209, 121],
  '9869': [3209, 5],
  '9876': [328, 3210],
  '9928': [174, 3225],
  '9934': [174, 3227],
  '9940': [174, 3223],
  '9941': [3233, 3232],
  '9944': [3235, 3232],
  '9959': [174, 3229],
  '9960': [531, 3229],
  '9975': [3240, 121],
  '9976': [3240, 5],
  '10006': [3242, 121],
  '10023': [3244, 121],
  '10024': [3244, 5],
  '10025': [138, 3246],
  '10026': [138, 3247],
  '10134': [138, 403],
  '10139': [1193, 74],
  '10176': [3275, 138],
  '10192': [5, 3281, 3282],
  '10214': [5, 3281, 3287],
  '10253': [5, 3281, 3294],
  '10276': [5, 3281, 3299],
  '10350': [138, 3306],
  '10351': [328, 3306],
  '10370': [138, 3307],
  '10434': [144, 3313],
  '10506': [138, 3251],
  '10507': [328, 3251],
  '10513': [138, 3314],
  '10678': [138, 2356],
  '10679': [328, 2356],
  '10682': [138, 3320],
  '10735': [415, 3155],
  '10741': [3065, 3155],
  '10824': [3327, 5],
  '10830': [3219],
  '10841': [1805, 3330],
  '10850': [328, 3215],
  '10852': [138, 3331],
  '10966': [881, 121, 94],
  '10967': [881, 5, 94],
  '10982': [3349, 121, 94],
  '10983': [3351, 121, 94],
  '11038': [415, 3153],
  '11041': [1434, 3153],
  '11044': [174, 3153],
  '11045': [3065, 3153],
  '11074': [174, 3361],
  '11118': [3371, 131],
  '11120': [3373, 131],
  '11126': [2372],
  '11159': [3376, 121],
  '11218': [1535, 121, 3382],
  '11228': [3355, 121, 94],
  '11242': [3387, 121, 94],
  '11243': [2483, 121],
  '11244': [2483, 5],
  '11262': [1153, 140],
  '11263': [3390, 140],
  '11265': [3392, 140],
  '11266': [3394, 140],
  '11267': [2601, 140],
  '11268': [413, 140],
  '11305': [3401, 3402],
  '11306': [3398, 3400],
  '11309': [3403, 138],
  '11312': [3405, 3406],
  '11313': [3407, 3408],
  '11315': [3409, 19],
  '11494': [3423],
  '11519': [413, 99],
  '11553': [174, 99],
  '11580': [3439, 185],
  '11586': [2494, 121],
  '11616': [3445],
  '11620': [173, 138],
  '11640': [3453],
  '11704': [3461, 5],
  '11710': [121, 3281, 3463],
  '11722': [174, 3466],
  '11759': [3481, 121],
  '11765': [415, 366],
  '11784': [3484, 121],
  '11881': [3493, 121],
  '12071': [2516, 1153],
  '12074': [2516, 19],
  '12082': [2516, 152],
  '12083': [2516, 1447],
  '12084': [2516, 325],
  '12085': [2516, 334],
  '12086': [2516, 343],
  '12103': [2517, 334],
  '12104': [2517, 343],
  '12107': [174, 2517],
  '12138': [3506, 334],
  '12139': [3506, 343],
  '12152': [174, 3545],
  '12164': [3553, 185],
  '12290': [3590, 185],
  '12339': [94, 3603, 118],
  '12344': [3602],
  '12355': [174, 3585],
  '12399': [2169, 1153],
  '12404': [3618, 1978],
  '12422': [1153],
  '12425': [1153, 1423],
  '12438': [150, 1153],
  '12439': [1153, 3627],
  '12444': [1153, 94],
  '12448': [1153, 146],
  '12451': [1153, 1434],
  '12455': [1153, 144],
  '12460': [1153, 1154],
  '12465': [1153, 1447],
  '12467': [1153, 334],
  '12474': [1153, 3632],
  '12476': [1153, 2240],
  '12524': [3640, 121, 94],
  '12538': [144, 1944],
  '12574': [152, 3643],
  '12582': [1782],
  '12590': [1794],
  '12594': [1792],
  '12605': [138, 1785],
  '12606': [1785],
  '12640': [835, 121],
  '12644': [835, 1136],
  '12645': [835, 325],
  '12682': [1423],
  '12688': [1423, 152],
  '12689': [152, 1423],
  '12696': [1423, 138],
  '12697': [138, 1423],
  '12701': [1423],
  '12716': [3664],
  '12726': [3668],
  '12777': [1923],
  '12778': [1923, 3675],
  '12779': [1923, 3676],
  '12780': [1923, 3677],
  '12796': [1926],
  '12820': [3604, 1943],
  '12828': [3683, 180],
  '12875': [3694, 3692],
  '12882': [3696, 3697],
  '12892': [328, 3699],
  '12984': [3724, 3725],
  '12985': [3724, 3727],
  '13056': [3143, 3733],
  '13057': [3734, 3733],
  '13254': [186, 3774],
  '13313': [3786],
  '13314': [3735],
  '13501': [138, 3844],
  '13506': [138, 3845],
  '13599': [138, 3853],
  '13656': [3724, 3864],
  '13688': [3868, 121],
  '13689': [3868, 5],
  '13839': [2544, 3884],
  '13841': [2544, 3886],
  '13843': [2544, 3888],
  '13894': [3233, 3904],
  '13968': [3914, 325],
  '14021': [3233, 3920],
  '14029': [3233, 3925],
  '14037': [3928, 2478],
  '14054': [174, 3938],
  '14055': [174, 3940],
  '14064': [3946, 3947],
  '14202': [3981, 174],
  '14208': [174, 3984],
  '14310': [3993, 185],
  '14366': [3998, 772],
  '14375': [1845, 121, 94],
  '14383': [1845, 94],
  '14399': [4004, 121, 94],
  '14406': [4010, 121, 94],
  '14407': [4010, 5, 94],
  '14409': [4012, 121, 94],
  '14412': [1211, 2256],
  '14413': [1211, 2268],
  '14414': [1211, 94],
  '14415': [1211, 121],
  '14417': [1211, 5],
  '14419': [1211, 343],
  '14431': [4017, 185],
  '14474': [1539, 121, 94],
  '14484': [4021, 121, 94],
  '14491': [4024, 121, 94],
  '14521': [491, 131],
  '14522': [413, 131],
  '14533': [4030, 131],
  '14545': [4031, 148],
  '14550': [4033, 4036],
  '14551': [4033, 325],
  '14553': [4037, 4040],
  '14601': [174, 4041],
  '14612': [174, 4043],
  '14627': [882, 4046],
  '14661': [4049],
  '14662': [4049],
  '14667': [4006],
  '14689': [4053, 772],
  '14698': [4062, 772],
  '14710': [4066, 772],
  '14711': [4067, 772],
  '14896': [4121, 4122],
  '14903': [491, 772],
  '14941': [144, 4129],
  '14943': [4130, 334],
  '14977': [4136, 337],
  '14979': [2552, 4138],
  '14980': [2552, 2256],
  '14987': [2552, 325],

In [66]:
df.loc[df['rxn_id'] == 410, 'smarts']

0    *C#N.O>>*C(N)=O
Name: smarts, dtype: object